# Generated by Django 4.2.11 on 2024-04-23 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0002_commentrecipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_recipes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
